export const SensorLocations = [
    'N/A',
    'Forehead',
    'Right Ear Canal',
    'Left Ear Canal',
    'Right Ear Lobe',
    'Left Eat Lobe',
    'Neck',
    'Right Wrist',
    'Left Wrist',
    'Right Upper Arm',
    'Left Upper Arm',
    'Right Tip of Thumb',
    'Left Tip of Thumb',
    'Right Base of Thumb',
    'Left Base of Thumb',
    'Right Tip of Finger',
    'Left Tip of Finger',
    'Right Base of Finger',
    'Left Base of Finger',
    'Chest',
    'Right Big Toe',
    'Left Big Toe'
];
